# -*- coding: utf-8 -*-
"""dtc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NA0yzShNKTNstez3DYQfVeXQMBWHh8mf
"""

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

df = pd.read_csv("C:/Users/DHRITI/Downloads/data.csv")

# df = pd.get_dummies(df, columns=['age', 'income', 'student', 'credit_rating','buys_computer'])
df = pd.get_dummies(df, columns=['age', 'income', 'student', 'credit_rating'])

df.head() 

X = df.drop('buys_computer', axis=1)
y = df['buys_computer']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy*100)
